---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: php
  pull: if-not-exists
  image: composer:1.9.1
  commands:
  - cp .env.example .env
  - ls -alh
  - composer install
  - ls -alh

- name: frontend
  pull: if-not-exists
  image: node:10.18.1
  commands:
  - npm i
  - npm run production
  - pwd
  - sudo find . -type f -exec chmod 664 {} +
  - sudo find . -type d -exec chmod 775 {} +
  - sudo chmod +x artisan
  - sudo chown -R www-data:www-data .
  - ls -alh

- name: Deploy to server without git & .env
  deploy:
    image: drillster/drone-rsync
    hosts:
      from_secret: SSH_SERVER
    user:
      from_secret: SSH_USER
    key:
      from_secret: SSH_PRIVATE_KEY
    source: *
    target: /var/www/drone_ci
    include: [ "*.**" ]
    exclude: [ ".git*", ".env" ]
